### ISSUE TITLE
Some issues in requirements

### ISSUE THREAD

**Issue by MaiNorapong** [Ing140943/Ku-polls-2020#1]
> 2.&nbsp;The polls should set a deadline for the vote.

A poll can't set a deadline. Did you mean each poll should have a deadline for voting?

> 3.&nbsp;The polls allow the user to modify answers for the polls.

Can users change their answer whenever? After the deadline as well? If not, you should write it explicitly.

What about voting? When can users vote? Can just about anyone vote?

> 4.&nbsp;The user should see questions after the result is announced.

What do you mean by this?

**Comment by Ing140943** [comment]
Already fix my answer, please check again.
